### ISSUE TITLE
Cython Installation issue?

### ISSUE THREAD

**Issue by texasraj** [tr8dr/tseries-patterns#12]
Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-q2_n3ik8/tseries-patterns_3d5bb6f370834c15ab683f40b5484a9a/setup.py", line 6, in <module>
      from Cython.Build import cythonize
  ModuleNotFoundError: No module named 'Cython'

Can we have a simple python function for the label instead of Cython? I have created some ZigZag Pivot points manually, similar to this.

Thanks!

**Comment by tr8dr** [comment]
It would seem you do not have Cython installed?   Not sure what you mean by "Can we have a simple python function for the label instead of Cython"?

**Comment by texasraj** [comment]
Hello Jonathan,

 

Thanks for the response here. 

 

In my environment, Cython is not installed and not allowed it seems.

 

I have tried to create a simple python function for min/max points with a % of move .. instead of bps.

 

Well, I was trying to find the local min and max (zigzag points) after a fixed % of move.. 

 

How do we add tenacity ..just need to count the bars between current max_position and last max_position? Thank you very much!!!

 

def find_local_maximas(x, pct = 2):

    max_val = []

    max_pos = []

    for i in range(1, len(x)):

        if x[i] < x[i-1] *  (1 - pct/100):

            max_pos.append((i-1))

            max_val.append(x[i-1])

    return(max_pos, max_val)

 

def find_local_minimas(x, pct = 2):

    min_val = []

    min_pos = []

    for i in range(1, len(x)):

        if x[i] > x[i-1]* (1 + pct/100): 

            min_pos.append((i-1))

            min_val.append(x[i-1])

    return(min_pos, min_val)

 

max_pos, max_val = find_local_maximas(stock_data.close, 5)

min_pos, min_val = find_local_minimas(stock_data.close, 5)

**Comment by tr8dr** [comment]
I am at a loss as to why you are getting this error.  requirements.txt is definitely part of the project.  You might want to try to clone the repository and install from source.

**Comment by texasraj** [comment]
Yah, I have installed all the modules from requirements.txt .. it still fails .. may be, because of the python virtualenv?

**Comment by texasraj** [comment]
Figured out.. thanks.. I was trying to install it as a pip module.. but i've run setup now.. thanks
