### ISSUE TITLE
unable to install library: No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by tsferro2** [tr8dr/tseries-patterns#13]
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Warning: passing language='c++' to cythonize() is deprecated. Instead, put "# distutils: language=c++" in your .pyx or .pxd file(s)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\...\AppData\Local\Temp\pip-install-syl2p25o\tseries-patterns_1ba9bee249ce4da2b7742e9c39f3411c\setup.py", line 45, in <module>
          install_requires=requirements(filename="requirements.txt"),
        File "C:\...\AppData\Local\Temp\pip-install-syl2p25o\tseries-patterns_1ba9bee249ce4da2b7742e9c39f3411c\setup.py", line 29, in requirements
          with io.open(filename, encoding='utf-8') as f:
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

**Comment by tr8dr** [comment]
I have not installed this on windows (only linux and osx).  That said others have been able to install on windows.   Are you using conda as your python distribution?   Also do you have Cython installed?

**Comment by tsferro2** [comment]
I was able to install on windows about a year ago using a different environment. I did install Cython this time around following an initial error. 

I am using:
 conda 4.11.0
Python 3.10.2

**Comment by tr8dr** [comment]
Windows environments are very challenging (where this stuff "just works" on unix based systems).   If you have changes you want to make to the library to get it to install for you, happy to accept.   I don't run windows, so I can only guess as to what you might need to change.

**Comment by tsferro2** [comment]
ok thanks for offering to update, though I am not sure what needs to be addressed at this stage. If I come up with something I will let you know.
